name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "android/**"
      - "lib/**"
      - "pubspec.yaml"

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (dev flavor)
        run: flutter build apk --debug --flavor dev -t lib/main.dart

      - name: Build APK (prod flavor)
        run: flutter build apk --debug --flavor prod -t lib/main.dart

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: flavor-apks
          path: |
            build/app/outputs/flutter-apk/app-dev-debug.apk
            build/app/outputs/flutter-apk/app-prod-debug.apk
